project_id = "fyklygjqxrvnyltooegf"

[functions.seed-test-users]
verify_jwt = false

[functions.drgreen-health]
verify_jwt = false

[functions.sync-strains]
verify_jwt = false

[functions.strain-knowledge]
verify_jwt = false

[functions.strain-medical-info]
verify_jwt = false

[functions.exchange-rates]
verify_jwt = false
