project_id = "jnhosxxahwljsggmtstb"

[functions.sync-strains]
verify_jwt = false

[functions.drgreen-proxy]
verify_jwt = false

[functions.drgreen-webhook]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = true

[functions.prescription-expiry-check]
verify_jwt = false

[functions.seed-test-users]
verify_jwt = false
